name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  build_and_push_image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      BRANCH: ${{ github.event.workflow_run.head_branch }}
      COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
      GHCR_REPO: ghcr.io/${{ github.repository }}
      HUB_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/fastapi-cicd-demo

    steps:
      - name: Checkout the exact commit that CI tested
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      # ---- Log in to GHCR ----
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---- Log in to Docker Hub ----
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_REPO }}
            ${{ env.HUB_REPO }}
          tags: |
            type=raw,value=latest,enable=${{ env.BRANCH == 'main' }}
            type=sha,format=short

      - name: Build and push to both registries
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
